services:
  moscowweatherarchives:
    image: moscowweatherarchives
    build:
      context: .
      dockerfile: MoscowWeatherArchives/Dockerfile
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
